name: Patch VBMeta

on:
  workflow_dispatch:
    inputs:
      ARCHITECTURE:
        description: 'Architecture (Para tu Moto E6 usa armeabi-v7a)'
        required: true
        default: 'armeabi-v7a'
        type: choice
        options:
        - x86_64
        - x86
        - arm64-v8a
        - armeabi-v7a # Corregido: era armeabi
      VBMETA_URL:
        description: 'URL directa de tu vbmeta.img (Google Drive o Dropbox)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out
      uses: actions/checkout@v3

    - name: Download VBMeta
      run: wget -O vbmeta.img "${{ github.event.inputs.VBMETA_URL }}"

    - name: Give Permission and Run Patch
      run: |
        # Usamos el nombre correcto de la carpeta del repo
        chmod +x ${{ github.event.inputs.ARCHITECTURE }}/vbmeta-disable-verification
        ./${{ github.event.inputs.ARCHITECTURE }}/vbmeta-disable-verification vbmeta.img

    - name: Upload to Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "vbmeta.img"
        tag: "patched-${{ github.run_id }}"
        token: ${{ secrets.GITHUB_TOKEN }}
        body: "VBMeta parchado para Moto E6 Play (Bali)"
