name: Patch VBMeta

on:
  workflow_dispatch:
    inputs:
      ARCHITECTURE:
        description: 'Arquitectura (Usa armeabi-v7a)'
        required: true
        default: 'armeabi-v7a'
        type: choice
        options:
        - x86_64
        - x86
        - arm64-v8a
        - armeabi-v7a

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out
      uses: actions/checkout@v3

    - name: Give Permission and Run Patch
      run: |
        # Cambiamos permisos al binario según la arquitectura elegida
        chmod +x ${{ github.event.inputs.ARCHITECTURE }}/vbmeta-disable-verification
        
        # Ejecutamos el parche sobre el vbmeta.img que está en la raíz
        ./${{ github.event.inputs.ARCHITECTURE }}/vbmeta-disable-verification vbmeta.img

    - name: Upload to Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "vbmeta.img"
        tag: "patched-${{ github.run_id }}"
        token: ${{ secrets.GITHUB_TOKEN }}
        body: "VBMeta parchado exitosamente para Moto E6 Play (Bali)"
